export const specificationOptions = {
  detailed_spec: {
    title: "Detailed Specification",
    description: "",
    hours: 10,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  simple_token: {
    title: "Simple Token & Incentive",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
  decent_token: {
    title: "Decent Token & Incentive",
    description: "",
    hours: 65,
    hourly: 100,
    min_timeline: 5,
    max_timeline: 7,
    active: false,
  },
  complex_token: {
    title: "Complex Token & Incentive",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 7,
    max_timeline: 0,
    active: false,
  },
  token_simulation: {
    title: "Tokenomics Simulation",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
  go_to_market: {
    title: "Go-to-market strategy",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
  business_model: {
    title: "Business model, sustainability, or value capture strategy",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 0,
    active: false,
  },
};

export const contentOptions = {
  light_content: {
    title: "Light application content",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  heavy_content: {
    title: "Heavy application content and documentation",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
    active: false,
  },
  marketing_article: {
    title: "Marketing article releases",
    description: "",
    hours: 10,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  video_sizzlers: {
    title: "Video Sizzlers",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 7,
    active: false,
  },
  content_management_system: {
    title: "Content Management System",
    description: "",
    hours: 35,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
};

export const designOptions = {
  design_sprint: {
    title: "Design Sprint (5 day / 3 day)",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 7,
    active: false,
  },
  design_research: {
    title: "Design Research",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  user_stories: {
    title: "User Story Mapping / User Flows",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  information_architecture: {
    title: "Information Architecture / Sitemap",
    description: "",
    hours: 10,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 0,
    active: false,
  },
  wireframes: {
    title: "Low-fidelity Wireframes",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
  mockups: {
    title: "High-fidelity Mock-up",
    description: "",
    hours: 60,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  prototype: {
    title: "Clickable Prototype",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 0,
    active: false,
  },
  design_system: {
    title: "UI Components Library / Design System",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
    active: false,
  },
  user_testing_basic: {
    title: "User Testing / Validation (Basic)",
    description: "",
    hours: 60,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  user_testing_advanced: {
    title: "User Testing / Validation (Advanced)",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
    active: false,
  },
  marketing_website: {
    title: "Marketing Website",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 3,
    active: false,
  },
  logo_style_guide: {
    title: "Logo and Style Guide",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 3,
    active: false,
  },
  brand_book: {
    title: "Brand Book",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
    active: false,
  },
  illustrations: {
    title: "Graphic design / Illustrations",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
    active: false,
  },
};

export const developmentOptions = {
  light_web3: {
    title: "Light web3 Interactions",
    description: "single page, 1-2 method calls and event listening",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 4,
    active: false,
  },
  ui_light_web3: {
    title: "UI intensive but light web3 Interactions",
    description: "heavy layout and user experienc, lots of visualizations",
    hours: 80,
    hourly: 100,
    min_timeline: 6,
    max_timeline: 8,
    active: false,
  },
  heavy_web3: {
    title: "Heavy web3 interactions",
    description: "multiple pages, 3+ web3 calls, visualizations",
    hours: 150,
    hourly: 100,
    min_timeline: 10,
    max_timeline: 0,
    active: false,
  },
  smart_contract: {
    title: "Single Smart Contract",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
    active: false,
  },
  multiple_smart_contracts: {
    title: "Multiple Smart Contracts",
    description: "",
    hours: 300,
    hourly: 100,
    min_timeline: 7,
    max_timeline: 0,
    active: false,
  },
  need_audit: {
    title: "Needs Audit",
    description: "",
    hours: 300,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 0,
    active: false,
  },
  no_code_backend: {
    title: "No Code Backend",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  db_backend: {
    title: "Database & Backend Framework",
    description: "",
    hours: 200,
    hourly: 100,
    min_timeline: 6,
    max_timeline: 8,
    active: false,
  },
  fiat_integration: {
    title: "Fiat Integration",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
  subgraph: {
    title: "Subgraph",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
    active: false,
  },
};

export const allOptions: any = {
  specification: specificationOptions,
  content: contentOptions,
  design: designOptions,
  development: developmentOptions,
};
