export const specificationOptions = [
  {
    title: "Detailed Specification",
    description: "",
    hours: 10,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
  },
  {
    title: "Simple Token & Incentive",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
  },
  {
    title: "Decent Token & Incentive",
    description: "",
    hours: 65,
    hourly: 100,
    min_timeline: 5,
    max_timeline: 7,
  },
  {
    title: "Complex Token & Incentive",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 7,
    max_timeline: 0,
  },
  {
    title: "Tokenomics Simulation",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
  },
  {
    title: "Go-to-market strategy",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
  },
  {
    title: "Business model, sustainability, or value capture strategy",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 0,
  },
];

export const contentOptions = [
  {
    title: "Light application content",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
  },
  {
    title: "Heavy application content and documentation",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
  },
  {
    title: "Marketing article releases",
    description: "",
    hours: 10,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
  },
  {
    title: "Video Sizzlers",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 7,
  },
  {
    title: "Content Management System",
    description: "",
    hours: 35,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
  },
];

export const designOptions = [
  {
    title: "Design Sprint (5 day / 3 day)",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 7,
  },
  {
    title: "Design Research",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
  },
  {
    title: "User Story Mapping / User Flows",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
  },
  {
    title: "Information Architecture / Sitemap",
    description: "",
    hours: 10,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 0,
  },
  {
    title: "Low-fidelity Wireframes",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
  },
  {
    title: "High-fidelity Mock-up",
    description: "",
    hours: 60,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
  },
  {
    title: "Clickable Prototype",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 0,
  },
  {
    title: "UI Components Library / Design System",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
  },
  {
    title: "User Testing / Validation (Basic)",
    description: "",
    hours: 60,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
  },
  {
    title: "User Testing / Validation (Advanced)",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
  },
  {
    title: "Company Website",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 3,
  },
  {
    title: "Logo and Style Guide",
    description: "",
    hours: 40,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 3,
  },
  {
    title: "Brand Book",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 4,
    max_timeline: 6,
  },
  {
    title: "Graphic design / Illustrations",
    description: "",
    hours: 20,
    hourly: 100,
    min_timeline: 1,
    max_timeline: 2,
  },
];

export const developmentOptions = [
  {
    title: "Light web3 Interactions",
    description: "single page, 1-2 method calls and event listening",
    hours: 50,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 4,
  },
  {
    title: "UI intensive but light web3 Interactions",
    description: "heavy layout and user experienc, lots of visualizations",
    hours: 80,
    hourly: 100,
    min_timeline: 6,
    max_timeline: 8,
  },
  {
    title: "Heavy web3 interactions",
    description: "multiple pages, 3+ web3 calls, visualizations",
    hours: 150,
    hourly: 100,
    min_timeline: 10,
    max_timeline: 0,
  },
  {
    title: "Single Smart Contract",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 5,
  },
  {
    title: "Multiple Smart Contracts",
    description: "",
    hours: 300,
    hourly: 100,
    min_timeline: 7,
    max_timeline: 0,
  },
  {
    title: "Needs Audit",
    description: "",
    hours: 300,
    hourly: 100,
    min_timeline: 3,
    max_timeline: 0,
  },
  {
    title: "No Code Backend",
    description: "",
    hours: 30,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
  },
  {
    title: "Database & Backend Framework",
    description: "",
    hours: 200,
    hourly: 100,
    min_timeline: 6,
    max_timeline: 8,
  },
  {
    title: "Fiat Integration",
    description: "",
    hours: 100,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
  },
  {
    title: "Subgraph",
    description: "",
    hours: 50,
    hourly: 100,
    min_timeline: 2,
    max_timeline: 4,
  },
];
